<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>ARES-7 Ransomware Builder</AssemblyTitle>
    <AssemblyDescription>v9.0 MinGW Builder</AssemblyDescription>
    <RootNamespace>RansomwareBuilder</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
  <ItemGroup>
    <!-- MinGW встроен в ресурсы -->
    <EmbeddedResource Include="mingw.zip" />
  </ItemGroup>
</Project>
