<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>V-ransomware Builder</AssemblyTitle>
    <AssemblyDescription>v10.0 Patcher</AssemblyDescription>
    <RootNamespace>RansomwareBuilder</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="template.exe" />
  </ItemGroup>
</Project>
