<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>ARES-7 WinLocker Builder v2.0</AssemblyTitle>
    <RootNamespace>WinLockerBuilder</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>
