name: Build with EWDK ISO

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download EWDK ISO
      shell: pwsh
      run: |
        $url = "https://go.microsoft.com/fwlink/?linkid=2269817"
        $isoPath = "$env:TEMP\ewdk.iso"
        Invoke-WebRequest -Uri $url -OutFile $isoPath -UseBasicParsing
        
        # Монтирование
        $mount = Mount-DiskImage -ImagePath $isoPath -PassThru
        $driveLetter = ($mount | Get-Volume).DriveLetter
        
        # Копирование
        Copy-Item -Path "$driveLetter`:\*" -Destination "C:\EWDK" -Recurse -Force
        
        Dismount-DiskImage -ImagePath $isoPath
        
        echo "C:\EWDK\bin" >> $env:GITHUB_PATH
        
    - name: Build
      shell: cmd
      run: |
        call C:\EWDK\BuildEnv\setenv.bat /x64 /fre /build
        cd src
        build -cZ
        
    - uses: actions/upload-artifact@v4
      with:
        name: driver
        path: src\obj\*.sys
